language: c
script: asdf plugin test guile . --asdf-plugin-gitref $TRAVIS_BRANCH 'guile --version'

before_script:
  - git clone https://github.com/asdf-vm/asdf.git asdf
  - . asdf/asdf.sh
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export LDFLAGS="$LDFLAGS -L/usr/local/opt/libffi/lib"; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/local/opt/libffi/lib/pkgconfig"; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export LDFLAGS="$LDFLAGS -L/usr/local/opt/readline/lib"; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export CPPFLAGS="$CPPFLAGS -I/usr/local/opt/readline/include"; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/local/opt/readline/lib/pkgconfig"; fi
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - build-essential
      - curl
      - dirmngr
      - gnupg2
      - libffi-dev
      - libgc-dev
      - libgc1c2
      - libgmp-dev
      - libtool
      - libunistring-dev
      - libunistring0
      - xz-utils
    update: true
  homebrew:
    casks:
      - gpg-suite
    packages:
      - autoconf
      - automake
      - bdw-gc
      - gettext
      - gmp
      - gnu-sed
      - libffi
      - libtool
      - libunistring
      - pkg-config
      - readline
    update: true
